spring:
  application:
    name: payment-service
  profiles:
    active: development
  config:
    import: "optional:configserver:http://localhost:9690"
  cloud:
    config:
      name: db-config,kafka,payment-service
spring.cloud.compatibility-verifier.enabled: false
server.port: 8082